### ISSUE TITLE
Authenticate client Spotify accounts via Rails, HTTParty, and Ember; store user data

### ISSUE THREAD

**Issue by seandonn-boston** [seandonn-boston/into-client#3]
My app requires the ability for users to authenticate third party API's, such as Spotify, Netflix, Steam, and more, and I'm struggling to connect my app to the Spotify Web API in order for users to authenticate their Spotify account at the click of a button.

Please note, my naming convetion is not good right now. I'm simply trying to setup the primary objective and make semantic and naming adjustments after.

For reference, here is Spotify's auth flowchart:
![authg_authoriztioncode](https://user-images.githubusercontent.com/38230468/44592387-5ea70980-a78e-11e8-9bc8-f4755f2ff848.png)
_____
# Primary objective:
Setup the authentication pipeline, save user's Spotify account email to DB

## What's working:
- I've created a Spotify Dev Account and registered my App, granting me a `client_id` and `client_secret`
- Using [this hard-coded link](https://accounts.spotify.com/authorize/?client_id=c4b89345becb45f7b9289414554c088c&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A4741%2Fcallback&scope=user-read-email&state=abcdefghijklmnopqrstuvwxyz0123456789) I can perform application requests 1 and 2 (see Spotify flow chart) and retrieve the `access_token` necessary for step 3
   - Note, the redirect_url is localhost:4741/callback, meaning this action currently only works on my local machine. My backend code will generate this link using HTTParty on at the index action
- Using the generated `access_token` I can create another hard-coded link, [such as this](https://api.spotify.com/v1/me?access_token=BQDBwJRdDKqDkYgS-S7o4lNyqXtPX-PO9ok8JvsRsAHok3_ULDJJgsNYOka_DVetKVqpKNeQi5Kpnh6f_5iB5_9o_U_I_9P61GxzAOB-8UdGMBT2wankqOydwppRijzKUQ5TiU8Je-HC6lL__BHLoJQ), to retrieve my Spotify user data, granting me access to view a JSON object of my general account information - name, email, followers, user image, etc
   - to access more information, I must request a different scope paramter from the first step. Scope parameters are well [documented here](https://developer.spotify.com/documentation/general/guides/scopes/).

## What's not working:
- A client facing 'login' button for users to click and grant INTO access to their Spotify account.
- A client facing 'refresh' button for users to click and refresh their access token, thus granting my app a new access_token (they expire after 3600 second).
   - This refresh function will be tethered to the main INTO functionality, generate. Upon generate, each access_token the user permitted will run a refresh which ensures I can access the users information at that moment.
- Saving to the database, and displaying to the client the user's Spotify account email information.
_____
# Code
## Back end
app/controllers/albums_controller.rb
```ruby
# frozen_string_literal: true

require 'pry'

class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show update destroy]

  # GET /albums
  # This works, test it in incognito mode with:
  # https://accounts.spotify.com/authorize/?client_id=c4b89345becb45f7b9289414554c088c&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A4741%2Fcallback&scope=user-read-email&state=abcdefghijklmnopqrstuvwxyz0123456789
  def index
    @albums = HTTParty.get('https://accounts.spotify.com/authorize',
      :headers => { 'Content-Type' => 'application/json' },
      query: {
        'client_id' => ENV['SPOTIFY_CLIENT_ID'],
        'response_type' => 'code',
        'redirect_uri' => 'http://localhost:4741/callback',
        'scope' => 'user-read-private user-read-email',
        'state' => 'abcdefghijklmnopqrstuvwxyz0123456789'
      })
    render json: @albums
  end

  def example
    @access = HTTParty.post('https://accounts.spotify.com/api/token',
      :headers => { 'Accept' => 'application/json' },
      query: {
        'client_id' => ENV['SPOTIFY_CLIENT_ID'],
        'client_secret' => ENV['SPOTIFY_CLIENT_SECRET'],
        'grant_type' => 'authorization_code',
        'code' => params['code'],
        'redirect_uri' => 'http://localhost:4741/callback'
      })
    render json: @access
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def album_params
      params.fetch(:album, {})
    end
end
```

## Front End
app/templates/account.hbs
```
<p>These are the available API services which INTO connects with. Simply save your username of each service to start gathering information</p>
<h2>Enter a new Account</h2>
{{account-service/form account=model.account updateAccount='createAccount' spotifyAuth='spotifyAuth' editForm=false}}
<hr>
<button class='btn btn-primary' {{action 'spotifyAuth'}}>Login to Spotify</button>
<hr>
<h2>Accounts:</h2>
<ul>
  {{#each model.accounts as |account|}}
    {{account-service account=account removeAccount='removeAccount' updateAccount='updateAccount'}}
  {{/each}}
</ul>
```
app/routes/account.js
```
import Route from '@ember/routing/route'
import RSVP from 'rsvp'

export default Route.extend({
  model () {
    return RSVP.hash({
      accounts: this.get('store').findAll('account'),
      account: this.get('store').createRecord('account', {})
    })
  },
  actions: {
    createAccount (account) {
      account.save().then(() => this.refresh())
    },
    removeAccount (account) {
      account.destroyRecord()
    },
    updateAccount (account) {
      account.save()
    },
    spotifyAuth () {
      this.get('store').findAll('album')
    }
  }
})
```
_____
## What happens:
- The user clicks the `Login to Spotify` button
- Console says: `XHR finished loading: GET "http://localhost:4741/albums".`
- Numerous warnings are displayed as well, all of them similar to this with varying values in the quotes: `WARNING: Encountered "content-type" in payload, but no model was found for model name "content-type" (resolved model name using (unknown mixin).modelNameFromPayloadKey("content-type"))`
- My backend rails server terminal for localhost:4741 reads: `Started GET "/albums" for ::1 at 2018-08-24 12:10:34 -0400
Processing by AlbumsController#index as HTML
[active_model_serializers] Rendered ActiveModel::Serializer::Null with HTTParty::Response (1.3ms)
Completed 200 OK in 251ms (Views: 14.0ms | ActiveRecord: 0.0ms)`
- Nothing else seems to be happening

## What I think needs to happen:
- User clicks 'login' button
- A pop-up from Spotify is displayed asking if the user to grant my app access.
- The user interacts with the pop-up, granting access in order to continue.
- The user returns to the page where they first clicked the Spotify button, which is now greyed out, and beside the button is their account email.
_____
## Developers thoughts, or TL;DR:
I seem to be forgetting a crucial bit of onformation necessary for this to work. Essentially this whole post boils down to one question. How do I make the backend run when I press a button on the front end? In context, how do I trigger albums#index in the controller when I press 'Login' on the front end?

**Comment by cpearce31** [comment]
The answer to this question:
>  In context, how do I trigger albums#index in the controller when I press 'Login' on the front end?

Is to make an AJAX request to a certain verb/path combo, and have a route in `route.rb` that handles that verb/path combo and routes it to the correct controller action. So, e.g. make a `GET` to `/albums` and have `get '/albums' => 'albums#index'` in `routes.rb`.

**Comment by seandonn-boston** [comment]
So already in my routes.rb file I have some routes setup for /albums and /callback:
```ruby
# frozen_string_literal: true

Rails.application.routes.draw do
  # RESTful routes
  resources :examples, except: %i[new edit]
  resources :users, only: %i[index show update]
  resources :accounts, except: %i[new edit]
  # resources :albums, except:

  # Custom routes
  post '/sign-up' => 'users#signup'
  post '/sign-in' => 'users#signin'
  delete '/sign-out' => 'users#signout'
  patch '/change-password' => 'users#changepw'
  get '/albums' => 'albums#index'
  get '/callback' => 'albums#example'
end
```
But I don't have an AJAX call so I'll try to connect that now

**Comment by seandonn-boston** [comment]
# OK NEWS!
So I've been trying to connect my ember-ajax request to the backend and I was terribly unsuccessful UNTIL I wrote the following code. Now keep in mind, this GET request is still not doing what I want it to do, however it is doing something without spitting back any errors! So that's something! Ok, so here's the code and I'll explain my additions after:

### app/templates/account.hbs
```hbs
<p>These are the available API services which INTO connects with. Simply save your username of each service to start gathering information</p>
<h2>Enter a new Account</h2>
{{account-service/form account=model.account updateAccount='createAccount' spotifyAuth='spotifyAuth' editForm=false}}
<hr>
<a  href="https://accounts.spotify.com/authorize/?client_id=c4b...88c&response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A7165%2Faccount&scope=user-read-email&state=abcdefghijklmnopqrstuvwxyz0123456789">Login to Spotify with hardcoded link</a>
<br>
<button class='btn btn-primary' {{action 'spotifyAuth'}}>Login to Spotify</button>
<hr>
<h2>Accounts:</h2>
<ul>
  {{#each model.accounts as |account|}}
    {{account-service account=account removeAccount='removeAccount' updateAccount='updateAccount'}}
  {{/each}}
</ul>
```

### app/routes/account.js
```js
import Ember from 'ember'
import Route from '@ember/routing/route'
import RSVP from 'rsvp'

export default Route.extend({
  ajax: Ember.inject.service(),
  model () {
    return RSVP.hash({
      accounts: this.get('store').findAll('account'),
      account: this.get('store').createRecord('account', {})
    })
  },
  actions: {
    createAccount (account) {
      account.save().then(() => this.refresh())
    },
    removeAccount (account) {
      account.destroyRecord()
    },
    updateAccount (account) {
      account.save()
    },
    spotifyAuth () {
      this.get('ajax').request('/albums')
    }
  }
})
```
## Changes
In the handlebars file there are two primary additions - an `<a>` tag linking to a hard-coded link of what `albums#index` should be creating (note this link cannot be hard-coded because of the secret key contained within it, which I've substituted in this comment), and a `<button>` tag performing the spotifyAuth action, which is performing an AJAX get request to `/albums` of the backend.

## What happens:
### a tag
When the `<a>` tag is clicked, the app redirects to the Spotify authentication page which asks the user to authenticate their data to be used by my app, and after the user accepts the authentication that user is redirected back to my client link, currently set to localhost:7165/accounts. Admittedly, I'm unsure if this is properly performing step 1 and 2 of the Spotify authentication flow chart - it seems to only be performing step 1. It's not that big a deal however considering this is for demo purposes only and not the actual thing I want working... 

### button
When the `<button>` is clicked, the console reads
```console
XHR finished loading: OPTIONS "http://localhost:4741/albums"
```
and
```console
XHR finished loading: GET "http://localhost:4741/albums"
```
and my terminal reads
```terminal
Started GET "/albums" for ::1 at 2018-08-27 11:03:13 -0400
Processing by AlbumsController#index as HTML
[active_model_serializers] Rendered ActiveModel::Serializer::Null with HTTParty::Response (1.14ms)
Completed 200 OK in 193ms (Views: 2.7ms | ActiveRecord: 0.0ms)
```
This tells me that step 1 is being performed, however I am not able to see the `code` or `state` which I expect to have returned... somewhere. I'm not sure where it should be returned.
Additionally, when the button is clicked, there is no Spotify Authentication page that appears. Nothing actually happens for the client view.

## Next Steps:
Answer the following:
- What happens on the backend when the button is clicked - is it actually hitting the get request route?
- If it is hitting the get request route, why is the authentication page not appearing?
I need to make the GET request to actually perform the actual GET request so that the link is generated through HTTParty and the authentication page appears from Spotify.
